### ISSUE TITLE
학번생성문제

### ISSUE THREAD

**Issue by callor** [Kwinhui/Biz-2023-11-505-java#3]
![image](https://github.com/Kwinhui/Biz-2023-11-505-java/assets/23270330/6a1a1466-6dad-498a-8059-5f2cbe4df144)

코드 상으로는 정상적으로 학번이 연번으로 생성되고 있으나
데이터 오류가 발생할 확률이 있습니다.
아래 부분의 코드를 for 반복문 내에서 수행하는 것이 좋겠습니다

![image](https://github.com/Kwinhui/Biz-2023-11-505-java/assets/23270330/a76caa01-81ab-41cc-bb50-b76e6ea60689)

**Comment by Kwinhui** [comment]
수정했습니다 감사합니다!
